steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone ${CI_REPO_CLONE_URL} .

  - name: run-tests
    image: python:3.11
    commands:
      - pip install pytest
      - pytest

  - name: sonar-scan
    image: sonarsource/sonar-scanner-cli
    secrets: [ SONAR_TOKEN, SONAR_URL ]
    commands:
      - >
        sonar-scanner
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.host.url=$SONAR_URL
        -Dsonar.projectKey=dummy-app
        -Dsonar.sources=.

  - name: notify
    image: curlimages/curl
    secrets: [ WEBHOOK_URL ]
    commands:
      - >
        echo "Build completed: $CI_COMMIT_SHA" |
        curl -X POST -H "Content-Type: text/plain" $WEBHOOK_URL

  - name: push-to-github
    image: alpine/git
    secrets: [ GITHUB_TOKEN ]
    when:
      status: [ success ]
    commands:
      - git remote add github https://$GITHUB_TOKEN@github.com/Magiciian/dummy-app.git
      - git push github HEAD:main
