when:
  - event: push
    branch: test

steps:

  - name: run-tests
    image: python:3.11
    commands:
      - pip install pytest
      - pytest

  - name: notify
    image: curlimages/curl
    environment:
      WEBHOOK_URL:
        from_secret: WEBHOOK_URL
    commands:
      - echo "Build completed: $CI_COMMIT_SHA"
      - >
        curl -X POST -H "Content-Type: application/json"
        --data "{\"text\": \"Build completed: $CI_COMMIT_SHA\"}"
        "$WEBHOOK_URL"

  - name: push-to-github
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      status:
        - success
    commands:
      - rm -rf .git
      - git init
      - git remote add origin "${CI_REPO_CLONE_URL}"
      - git fetch origin test
      - git checkout -b test origin/test

      - git remote add github "https://${GITHUB_TOKEN}@github.com/Magiciian/dummy-app.git"
      - git push github test:main
