pipeline:
  clone:
    image: alpine/git
    commands:
      - git clone ${CI_REPO_CLONE_URL} .

  run-tests:
    image: python:3.11
    commands:
      - pip install pytest
      - pytest

  sonar-scan:
    image: sonarsource/sonar-scanner-cli
    secrets: [ sonar_token ]
    commands:
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_URL

  notify:
    image: curlimages/curl
    commands:
      - echo "Build completed for $CI_COMMIT_SHA" | curl -X POST -H "Content-Type: text/plain" $WEBHOOK_URL

  push-to-github:
    image: alpine/git
    secrets: [ github_token ]
    when:
      status: success
    commands:
      - git remote add github https://$GITHUB_TOKEN@github.com/<yourname>/dummy-app.git
      - git push github HEAD:main
